POST http://localhost:3000/proprietario
Content-Type: application/json

{
  "cpf": "12234678909",
  "nome": "Camargo",
  "telefone": "47995568293"
}

###
GET http://localhost:3000/proprietario
Content-Type: application/json

###
GET http://localhost:3000/proprietario
Content-Type: application/json

###
POST http://localhost:3000/veiculo
Content-Type: application/json

{
  "placa": "JDD3987",
  "modelo": "Ferrari",
  "preco": "8000.00",
  "cpfProprietario": "12345678901"
}

###
GET http://localhost:3000/veiculo

###
GET http://localhost:3000/veiculo/proprietario/

###
GET http://localhost:3000/veiculo/tipo/Luxo

### 
PUT http://localhost:3000/veiculo/JKD3987
Content-Type: application/json

{
  "modelo": "Corsa"
}